import SwiftUI
import CookCore
import UniformTypeIdentifiers

struct DataPrivacySettingsView:View{
 @Environment(CookStore.self)private var store
 @State private var export=false;@State private var doc=SettingsExportDocument(data:Data());@State private var confirmLocal=false;@State private var confirmAccount=false;@State private var message:String?
 var body:some View{List{Section("Your data"){Button("Export All Local Data"){prepareExport()};NavigationLink("What Cook Stores"){StoredDataView()};NavigationLink("Privacy Summary"){PrivacySummaryView()}};Section("Delete"){Button("Delete All Local Data",role:.destructive){confirmLocal=true};HStack { Text("Delete Cook Account & Cloud Data").foregroundStyle(.secondary); Spacer(); Text("Sign in required").font(CookTheme.text(12, weight: .regular, relativeTo: .caption)).foregroundStyle(.secondary) }}}.navigationTitle("Data & Privacy").navigationBarTitleDisplayMode(.inline).fileExporter(isPresented:$export,document:doc,contentType:.json,defaultFilename:"Cook-Export"){_ in}.confirmationDialog("Delete all local Cook data?",isPresented:$confirmLocal,titleVisibility:.visible){Button("Delete Local Data",role:.destructive){do{try CookLocalDataCleanup.reset(store:store);message="Local data deleted."}catch{message=error.localizedDescription}}}.confirmationDialog("Delete Cook account?",isPresented:$confirmAccount,titleVisibility:.visible){Button("Delete Account & Cloud Data",role:.destructive){message="Connect a Cook account before deleting cloud data."}}message:{Text("This is separate from cancelling your App Store subscription.")}.alert("Data & Privacy",isPresented:.init(get:{message != nil},set:{if !$0{message=nil}})){Button("OK",role:.cancel){message=nil}}message:{Text(message ?? "")}}
 func prepareExport(){do{doc=SettingsExportDocument(data:try store.exportData());export=true}catch{message=error.localizedDescription}}
}
private struct SettingsExportDocument:FileDocument{
 static var readableContentTypes:[UTType]{[.json]};var data:Data
 init(data:Data){self.data=data};init(configuration:ReadConfiguration)throws{data=configuration.file.regularFileContents ?? Data()}
 func fileWrapper(configuration:WriteConfiguration)throws->FileWrapper{FileWrapper(regularFileWithContents:data)}
}
struct StoredDataView:View{var body:some View{List{Label("Recipes, notes and original sources",systemImage:"book");Label("Groceries and recipe references",systemImage:"basket");Label("Meal plan",systemImage:"calendar");Label("Local preferences and cooking sessions",systemImage:"gearshape")}.navigationTitle("What Cook Stores").navigationBarTitleDisplayMode(.inline)}}
struct PrivacySummaryView:View{var body:some View{ScrollView{VStack(alignment:.leading,spacing:18){Text("Privacy Summary").font(CookTheme.title(30));Text("Cook is designed as a private recipe utility. It does not publish your recipes to a public feed.");Text("Automated imports may send source material to Cook’s backend only when the import feature requires processing. Provider secrets remain server-side.");Text("App Store purchases are managed by Apple. Your App Store purchase identity and Cook recipe account are treated as separate identities.");Text("You can export local data and request deletion of your Cook account data from Settings.")}.padding()}.navigationTitle("Privacy").navigationBarTitleDisplayMode(.inline)}}

struct HelpCenterView:View{
 var body:some View{List{Section("Getting started"){NavigationLink("Add or import a recipe"){HelpArticleView(title:"Add or import a recipe",articleBody:"Use Add Recipe to paste a link, import text or a document, scan a photo, or create a recipe manually. Incomplete imports remain editable instead of inventing missing details.")};NavigationLink("Cook with timers"){HelpArticleView(title:"Cook with timers",articleBody:"Start Cooking opens a focused full-screen flow. Step timers can run independently, ingredients can be checked off, and Cook restores the session when possible.")};NavigationLink("Plan meals and shop"){HelpArticleView(title:"Plan meals and shop",articleBody:"Add saved recipes to the Meal Plan, then add ingredients to Groceries. Cook preserves recipe sources and only consolidates compatible quantities.")}};Section("Troubleshooting"){NavigationLink("Subscription not showing"){HelpArticleView(title:"Subscription not showing",articleBody:"Check that you are using the intended Cook account and App Store account. Then open Subscription and choose Restore Purchases. Restoring an App Store purchase does not select which Cook cloud account contains your recipes.")};NavigationLink("Sync problems"){HelpArticleView(title:"Sync problems",articleBody:"Open Cloud Sync to review account, last sync and status. Your local library remains available while sync is unavailable.")};NavigationLink("Import needs review"){HelpArticleView(title:"Import needs review",articleBody:"Cook keeps the original source and marks uncertain or missing recipe details for review rather than guessing quantities or steps.")}}}.navigationTitle("Help & Support").navigationBarTitleDisplayMode(.inline)}
}
private struct HelpArticleView:View{let title:String;let articleBody:String;var body:some View{ScrollView{VStack(alignment:.leading,spacing:16){Text(title).font(CookTheme.title(30));Text(articleBody).font(CookTheme.text(17, weight: .regular, relativeTo: .body))}.padding()}.navigationTitle(title).navigationBarTitleDisplayMode(.inline)}}

struct AboutSettingsView:View{
 var body:some View{List{Section{HStack{Image(systemName:"leaf.fill").font(.system(size:34)).foregroundStyle(CookTheme.accentForeground);Text("Cook").font(CookTheme.title(28))}};Section("App"){LabeledContent("Version",value:CookVersion.display);NavigationLink("Open Source Licenses"){LicensesView()};NavigationLink("Acknowledgements"){AcknowledgementsView()}};Section("Legal"){Link("Apple Standard EULA",destination:URL(string:"https://www.apple.com/legal/internet-services/itunes/dev/stdeula/")!)}}.navigationTitle("About Cook").navigationBarTitleDisplayMode(.inline)}
}
private struct LicensesView:View{var body:some View{List{Section("Lora"){Text("Copyright The Lora Project Authors. Licensed under the SIL Open Font License 1.1.")};Section("System frameworks"){Text("SwiftUI, StoreKit, AuthenticationServices, Vision and related Apple frameworks are used under Apple platform terms.")}}.navigationTitle("Licenses").navigationBarTitleDisplayMode(.inline)}}
private struct AcknowledgementsView:View{var body:some View{ScrollView{Text("Cook’s interaction model is informed by established private recipe managers: collect recipes, organize them, cook step-by-step, plan meals and shop from ingredients. Cook’s implementation and visual system remain its own.").padding()}.navigationTitle("Acknowledgements").navigationBarTitleDisplayMode(.inline)}}
