-- Developer: gengyun
-- Purpose: Save and delete AI providers atomically without rewriting secrets or history.
-- Generated by `supabase migration new`; ordered after the existing 17-migration chain.

create or replace function public.admin_ai_save_provider(
  p_provider_id uuid,
  p_name text,
  p_base_url text,
  p_model text,
  p_active boolean,
  p_secret jsonb default null
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_provider public.ai_providers%rowtype;
  v_model public.ai_models%rowtype;
  v_model_ids uuid[];
  v_secret_ref text;
  v_referenced boolean;
begin
  if p_name is null or char_length(btrim(p_name)) not between 1 and 120
    or p_base_url is null or char_length(p_base_url) not between 1 and 2048
    or p_model is null or char_length(btrim(p_model)) not between 1 and 256
    or p_active is null then
    raise sqlstate '22023' using message = 'Invalid provider input';
  end if;

  -- JSON/array references lack foreign-key locks. Block their writers for this
  -- short transaction, before checking history; use the same order in delete.
  lock table public.ai_providers, public.ai_models, public.ai_routes,
    public.ai_usage_events, public.admin_audit_logs, public.ai_provider_health
    in share row exclusive mode;

  if p_provider_id is not null then
    select * into v_provider from public.ai_providers where id = p_provider_id;
    if not found then
      raise sqlstate 'PT404' using message = 'Provider not found';
    end if;
    select coalesce(array_agg(id), '{}'::uuid[]) into v_model_ids
      from public.ai_models where provider_id = p_provider_id;
    select * into v_model from public.ai_models where provider_id = p_provider_id
      order by enabled desc, created_at, id limit 1;

    if p_model is distinct from v_model.upstream_model_id then
      if cardinality(v_model_ids) <> 1 then
        raise sqlstate 'PT409' using message = 'Model changes require one unreferenced model';
      end if;
      select exists (
        select 1 from public.ai_routes r
          where r.primary_model_id = any(v_model_ids) or r.fallback_model_ids && v_model_ids
        union all
        select 1 from public.ai_usage_events u
          where u.provider_id = p_provider_id or u.model_id = any(v_model_ids)
            or u.final_model_id = any(v_model_ids)
            or exists (select 1 from unnest(v_model_ids) m(id)
              where strpos(lower(u.attempted_models::text), m.id::text) > 0)
            or strpos(lower(u.attempted_models::text), p_provider_id::text) > 0
        union all
        select 1 from public.admin_audit_logs a
          where strpos(lower(to_jsonb(a)::text), p_provider_id::text) > 0
            or exists (select 1 from unnest(v_model_ids) m(id)
              where strpos(lower(to_jsonb(a)::text), m.id::text) > 0)
      ) into v_referenced;
      if v_referenced then
        raise sqlstate 'PT409' using message = 'Provider model has route or history references';
      end if;
      -- Preserve identity and existing capabilities/pricing metadata.
      update public.ai_models set upstream_model_id = p_model, display_name = p_model
        where id = v_model.id returning * into v_model;
    end if;
    v_secret_ref := v_provider.secret_ref;
  elsif p_secret is null then
    raise sqlstate '22023' using message = 'Provider creation requires a key';
  end if;

  if p_secret is not null then
    if jsonb_typeof(p_secret) is distinct from 'object'
      or p_secret->>'key_version' is distinct from '2'
      or coalesce(p_secret->>'secret_ref', '') = ''
      or coalesce(p_secret->>'ciphertext', '') !~ '^[A-Za-z0-9_-]+$'
      or coalesce(p_secret->>'nonce', '') !~ '^[A-Za-z0-9_-]{16}$' then
      raise sqlstate '22023' using message = 'Invalid v2 secret envelope';
    end if;
    v_secret_ref := p_secret->>'secret_ref';
    -- INSERT only: reused references fail and roll back the whole save.
    insert into public.ai_secrets(secret_ref, ciphertext, nonce, key_version)
      values (v_secret_ref, p_secret->>'ciphertext', p_secret->>'nonce', 2);
  end if;

  if p_provider_id is null then
    insert into public.ai_providers(name, base_url, enabled, secret_ref)
      values (p_name, p_base_url, p_active, v_secret_ref) returning * into v_provider;
    insert into public.ai_models(provider_id, display_name, upstream_model_id)
      values (v_provider.id, p_model, p_model) returning * into v_model;
  else
    update public.ai_providers set name = p_name, base_url = p_base_url,
      enabled = p_active, secret_ref = v_secret_ref
      where id = p_provider_id returning * into v_provider;
  end if;

  return jsonb_build_object('id', v_provider.id, 'name', v_provider.name,
    'baseUrl', v_provider.base_url, 'model', v_model.upstream_model_id,
    'active', v_provider.enabled, 'apiKeyConfigured', v_provider.secret_ref is not null,
    'updatedAt', v_provider.updated_at);
end;
$$;

create or replace function public.admin_ai_delete_provider(p_provider_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_model_ids uuid[];
  v_referenced boolean;
begin
  lock table public.ai_providers, public.ai_models, public.ai_routes,
    public.ai_usage_events, public.admin_audit_logs, public.ai_provider_health
    in share row exclusive mode;
  if not exists(select 1 from public.ai_providers where id = p_provider_id) then
    raise sqlstate 'PT404' using message = 'Provider not found';
  end if;
  select coalesce(array_agg(id), '{}'::uuid[]) into v_model_ids
    from public.ai_models where provider_id = p_provider_id;
  select exists (
    select 1 from public.ai_routes r
      where r.primary_model_id = any(v_model_ids) or r.fallback_model_ids && v_model_ids
    union all
    select 1 from public.ai_usage_events u
      where u.provider_id = p_provider_id or u.model_id = any(v_model_ids)
        or u.final_model_id = any(v_model_ids)
        or exists (select 1 from unnest(v_model_ids) m(id)
          where strpos(lower(u.attempted_models::text), m.id::text) > 0)
        or strpos(lower(u.attempted_models::text), p_provider_id::text) > 0
    union all
    select 1 from public.admin_audit_logs a
      where strpos(lower(to_jsonb(a)::text), p_provider_id::text) > 0
        or exists (select 1 from unnest(v_model_ids) m(id)
          where strpos(lower(to_jsonb(a)::text), m.id::text) > 0)
  ) into v_referenced;
  if v_referenced then
    raise sqlstate 'PT409' using message = 'Provider has route or history references';
  end if;

  -- Only the unreferenced provider, models and transient health row cascade.
  -- Secrets are deliberately retained, including old versions and rotations.
  delete from public.ai_providers where id = p_provider_id;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.admin_ai_save_provider(uuid,text,text,text,boolean,jsonb)
  from public, anon, authenticated;
revoke all on function public.admin_ai_delete_provider(uuid)
  from public, anon, authenticated;
grant execute on function public.admin_ai_save_provider(uuid,text,text,text,boolean,jsonb)
  to service_role;
grant execute on function public.admin_ai_delete_provider(uuid) to service_role;
